name: BDD Tests and Report Publishing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código principal
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar PHP
      - name: ⚙️ Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        working-directory: Markdown2Video
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer require --dev behat/behat

      # Paso 4: Ejecutar pruebas BDD
      - name: Run Behat tests
        run: |
          Markdown2Video/vendor/bin/behat --format=pretty --format=junit --out=reports/junit --format=html --out=reports/html

      # Paso 5: Guardar reportes como artefacto
      - name: Upload test reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: bdd-reports
          path: reports

      # Paso 6: Publicar en gh-pages (solo si es main o develop)
      - name: Publish BDD Reports to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          mkdir -p gh-pages/bdd
          cp -R reports/html/* gh-pages/bdd/

          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update BDD reports - $(date)"
            git push origin gh-pages
          fi
