name: Mutation Testing and Deployment

on:
  push:
    branches: [main]
  pull_request:

jobs:
  infection:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug

      - name: 🔓 Permitir plugin infection/extension-installer
        working-directory: Markdown2Video
        run: composer config --no-plugins allow-plugins.infection/extension-installer true

      - name: 📦 Instalar dependencias (PHPUnit + Infection)
        working-directory: Markdown2Video
        run: |
          composer install --prefer-dist --no-progress
          if [ ! -f vendor/bin/phpunit ]; then
            composer require --dev phpunit/phpunit
          fi
          if [ ! -f vendor/bin/infection ]; then
            composer require --dev infection/infection
          fi
            chmod +x vendor/bin/phpunit  # 👈 Agrega esta línea

      - name: 🧪 Ejecutar pruebas con cobertura
        run: |
          mkdir -p coverage
          
          # Ejecutar PHPUnit con los formatos correctos
          XDEBUG_MODE=coverage ./Markdown2Video/vendor/bin/phpunit \
            --coverage-clover=coverage/clover.xml \  # Formato Clover para Infection
            --log-junit=coverage/junit.xml \        # Formato JUnit (NO renombrar)
            --coverage-html=coverage/html \          # Opcional: HTML para visualización
            tests
      
          # Verificar que se generaron los archivos
          ls -la coverage/

      - name: 🧬 Ejecutar Infection (pruebas de mutación)
        run: |
          # Verificar que coverage existe
          ls -la coverage/
        
          # Asegurar permisos de ejecución
          chmod +x Markdown2Video/vendor/bin/phpunit

          Markdown2Video/vendor/bin/infection \
          --coverage=coverage \
          --logger-html=infection-report \
          --initial-tests-php-options="-d xdebug.mode=coverage" \
          --verbose

      - name: 📤 Subir reporte de mutación como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: Markdown2Video/infection-report/

  deploy-ghpages:
    needs: infection
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Descargar artefacto del reporte
        uses: actions/download-artifact@v4
        with:
          name: mutation-report
          path: reports/mutation

      - name: 🚀 Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports
          destination_dir: reports
          keep_files: true
