name: Sync to VPS

env:
  PHP_VERSION: 8.1
  COMPOSER_VERSION: 2.1

on:
  push:
    branches:
      - main  # Puedes configura r para que solo se ejecute al hacer push a la rama principal (o la que prefieras)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: sync files to vps
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Instalar las herramientas necesarias en el runner de GitHub Actions
        sudo apt-get update
        sudo apt-get install -y sshpass rsync

        # Definir el servidor de destino
        TARGET_HOST="root@3.140.27.154"

        # Lista de dependencias de sistema para que Marp CLI (Puppeteer) funcione en un servidor Linux
        DEPS="libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 libgtk-3-0"

        echo ">>> Instalando dependencias en el servidor remoto..."
        sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no $TARGET_HOST "apt-get update && apt-get install -y $DEPS"

        echo ">>> Sincronizando los archivos de la aplicación..."
        sshpass -p "$SSHPASS" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Markdown2Video/ $TARGET_HOST:/var/www/html/Markdown2Video/