name: Sync to VPS

env:
  PHP_VERSION: 8.1
  COMPOSER_VERSION: 2.1

on:
  push:
    branches:
      - main  # Puedes configura r para que solo se ejecute al hacer push a la rama principal (o la que prefieras)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

    - name: Install dependencies and Sync files
      run: |
        TARGET_HOST="root@3.140.27.154"
        DEPS="libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 libgtk-3-0"

        echo ">>> Installing dependencies on remote server..."
        ssh -o StrictHostKeyChecking=no $TARGET_HOST "apt-get update && apt-get install -y $DEPS"

        echo ">>> Syncing application files..."
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Markdown2Video/ $TARGET_HOST:/var/www/html/Markdown2Video/